sudo: required
language: generic
service:
        - docker

before_install:
        - docker build -t uazadi/docker-react  -f Dockerfile.dev .

script:
        - docker run -e CI=true uazadi/docker-react npm run test -- --coverage


